name: Register new institution
description: Register a new instituion conducting CORDEX-CMIP6 simulations for inclusion into CV.
title: "institution_id registration of ..."
labels: ["Register institution_id"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time!

  - type: input
    id: institution_id
    attributes:
      label: institution_id
      description: >
        An identifier for the institution that is responsible for generating
        and providing CORDEX simulations.
        No spaces, dots or underscores are allowed.
        Hyphens are typically used to separate community names from the specific institution performing the run (e.g. COMM-INST), or to separate different institution acronyms partnering to contribute a given simulation (e.g. INST1-INST2).
      placeholder: ex. `GERICS`
    validations:
      required: true

  - type: input
    id: institution
    attributes:
      label: institution
      description: Full name, city, country of the institution that is responsible for CORDEX simulations. If several institutions are registered as a single provider, use a semicolon to separate their full names and place them into brackets. E.g. `INST1 [Full name 1, city1, country1]; INST2 [Full name 2, city2, country2]`
      placeholder: ex. `Climate Service Center Germany, Helmholtz Centre hereon GmbH, Hamburg, Germany`
    validations:
      required: true
