name: update controlled vocabulary

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Update CV'

  push:
    paths:
      - 'CORDEX_*.json'
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_cv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout cordex-cv
      uses: actions/checkout@v4

    - name: checkout cordex cmor tables
      uses: actions/checkout@v4
      with:
        repository: WCRP-CORDEX/cordex-cmip6-cmor-tables
        path: tables
        token: ${{ secrets.TABLE_ACCESS_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pre-commit

    - name: Update controlled vocabulary
      run: |
        python scripts/create-cv.py
        mv CORDEX_CV.json tables/Tables

    - name: Check if there are any changes
      id: verify_diff
      run: |
        cd tables
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        cd tables
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        (pre-commit run --all-files) || true
        git commit Tables/CORDEX_CV.json -m "CV update"
        git status
        git push
